### PR TITLE
Prevent divide by 0

### LINKED ISSUE #273: Please Help i dont understand
An unexpected error occurred
java.lang.ArithmeticException: / by zero
	at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:55)
	at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:336)
	at java.lang.Thread.run(Unknown Source
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/7576544/enchcracker.log)
)

### PR DESCRIPTION
**Pull request by Phoenix-Starlight**
Added in a ternary operation so that if it evaluates to 0 it will become 1 instead. (The only issue I can see is that the user's computer dies or hangs possibly.. although then everything is running on the same thread/core)

EDIT: Fixes #273

### CODE REVIEW

File: src/enchcracker/cracker/JavaSingleSeedCracker.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public void resetCracker() {
 	@Override
 	public void firstInput(int bookshelves, int slot1, int slot2, int slot3) {
 		abortRequested.set(false);
-		final int threadCount = Runtime.getRuntime().availableProcessors() - 1; // always leave one for OS
+		final int threadCount = Runtime.getRuntime().availableProcessors() - 1 != 0 ? Runtime.getRuntime().availableProcessors() - 1 : 1; // always leave one for OS; ternary op to ensure that it is never zero
```
Comment (DJtheRedstoner) [inline src/enchcracker/cracker/JavaSingleSeedCracker.java:54]:
```suggestion
		final int threadCount = Math.max(Runtime.getRuntime().availableProcessors() - 1, 1); // always leave one for OS but ensure at least 1 processor is used
```

To me this is easier to read than the ternary and doesn't duplicate the calculation.

**Review by Earthcomputer — APPROVED** [review]
